config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations', 
    confirmations: 'users/confirmations'
  }

  devise_for :admins, skip: [:registrations]
  devise_scope :admin do
    unauthenticated :admin do
      root 'devise/sessions#new'
    end
    authenticated :admin do
      devise_for :admins, only: [:registrations], controllers: { registrations: 'admins/registrations' }
      root to: "customize#show", as: :authenticated_user
      resources :admins, only: [:index, :show]
      resource :customize, controller: 'customize', except: [:edit, :new] do
        get 'data', to: 'data'
      end
      resource :compositional_role_variable, as: 'env', path: 'env' do
        get 'env_vars', to: 'get_env_vars'
        post 'update', to: 'update', as: 'update_env'
      end 
      resource :services, controller:'services', except: [:edit, :new]
      namespace :rundeck do
        post 'migrate', to: 'migrate'
        get 'migration_status', to: 'migration_status'
        post 'run_compositional_role', to: 'run_compositional_role'
      end
      namespace :execution_abstraction do
        # Post Methods for Running Commands
        post 'migrate', to: 'post_migrate', action:'post_migrate'
        post 'compositional_role', to: 'post_compositional_role', action: 'post_compositional_role'
        post 'health_check', to: 'post_health_check', action: 'post_health_check'
        post 'run_backup', to: 'post_run_backup', action: 'post_run_backup'
        post 'set_rundeck_key', to: 'set_rundeck_key', action: 'set_rundeck_key'
        post 'service_state', to: 'post_service_state', action: 'post_service_state'
        post 'run_ourcompose_role', to: 'post_run_ourcompose_role', action: 'post_run_ourcompose_role'
        post 'env_configuration', to: 'post_env_configuration', action: 'post_env_configuration'

        # Get Requests for latest
        get 'migration', to: 'get_migration', action: 'get_migration'
        get 'compositional_role', to: 'get_compositional_role', action: 'get_compositional_role'
        get 'health_check', to: 'get_health_check', action: 'get_health_check'
        get 'backup', to: 'get_backup', action: 'get_backup'
        get 'service_state', to: 'get_service_state', action: 'get_service_state'
        get 'env_configuration', to: 'get_env_configuration', action: 'get_env_configuration'

      end
      resource :proxy_logs, as: 'logs', path: 'logs', only: [:show] do
        get 'available', to: 'get_available_log_files', action: 'available_log_files'
        get 'get_file', to: 'get_log_file', action: 'log_file'
        get 'logfile_length', to: 'logfile_length', action: 'logfile_length'
      end
    end
  end

  get 'help', to: 'staticpages#help'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root 'staticpages#index'

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/_nav.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav" style="color: rgba(232, 230, 227, 0.5); background: rgba(0,0,0, .55)">
    <div class="container">
      <%= link_to root_path, class:"navbar-brand" do %>
        <img src="<%= asset_pack_path("media/images/LogoWithNameTransparentDark.png") %>" height="35" />
      <% end %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <% if admin_signed_in? %>
              <%= link_to "Manage Instance", customize_path, class:"nav-link js-scroll-trigger", style:"color: rgba(232, 230, 227, 0.5);" %>
            <% else %>
                <%= link_to "Manage Instance", new_admin_session_path, class:"nav-link js-scroll-trigger", style:"color: rgba(232, 230, 227, 0.5);" %>
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color: rgba(232, 230, 227, 0.5);" href="https://compositionalenterprises.ourcompose.com/bookstack/books">Docs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color: rgba(232, 230, 227, 0.5);" href="https://ourcompose.com">Billing & Support</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color: rgba(232, 230, 227, 0.5);" href="https://ourcomposecast.com">OurComposeCast</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color: rgba(232, 230, 227, 0.5);" href="https://reddit.com/r/ourcompose">Community</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color: rgba(232, 230, 227, 0.5);" href="https://gitlab.com/compositionalenterprises">Gitlab</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" style="color: rgba(232, 230, 227, 0.5);" href="https://compositionalenterprises.ourcompose.com/kanboard/public/board/245d06ce519a4deba6131ea58a65afa9efc0e6de584e04b08a81c4115322">Feature Roadmap</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

app/views/staticpages/help.erb
<%= render 'staticpages/nav' %>

<div class="container" style="padding-top:6%;">
    <%= link_to "Forgot your password?", new_admin_password_path, class:"nav-link" %>
    <%= link_to "Didn't receive confirmation instructions?", new_admin_confirmation_path, class:"nav-link" %>
</div>

app/views/staticpages/index.erb
<%= render 'staticpages/nav' %>

<header class="masthead" style="height: 100%;">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center" style="padding-bottom:20%;">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold"><%= Customization.first.tagline %></h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <% Service.all.each do |f| %>
            <% if f.url[0..7] == "https://" %>
              <%= link_to f.name.capitalize, f.url, class:"btn btn-primary btn-xl js-scroll-trigger" %>
            <% else %>
              <%= link_to f.name.capitalize, "https://" + f.url, class:"btn btn-primary btn-xl js-scroll-trigger" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
</header>