config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations', 
    confirmations: 'users/confirmations'
  }

  devise_for :admins, skip: [:registrations]
  devise_scope :admin do
    unauthenticated :admin do
      root 'devise/sessions#new'
    end
    authenticated :admin do
      devise_for :admins, only: [:registrations], controllers: { registrations: 'admins/registrations' }
      root to: "customize#show", as: :authenticated_user
      resources :admins, only: [:index, :show]
      resource :customize, controller: 'customize', except: [:edit, :new] do
        get 'data', to: 'data'
      end
      resource :compositional_role_variable, as: 'env', path: 'env' do
        get 'env_vars', to: 'get_env_vars'
        post 'update', to: 'update', as: 'update_env'
      end 
      resource :services, controller:'services', except: [:edit, :new]
      namespace :rundeck do
        post 'migrate', to: 'migrate'
        get 'migration_status', to: 'migration_status'
        post 'run_compositional_role', to: 'run_compositional_role'
      end
      namespace :execution_abstraction do
        # Post Methods for Running Commands
        post 'migrate', to: 'post_migrate', action:'post_migrate'
        post 'compositional_role', to: 'post_compositional_role', action: 'post_compositional_role'
        post 'health_check', to: 'post_health_check', action: 'post_health_check'
        post 'run_backup', to: 'post_run_backup', action: 'post_run_backup'
        post 'set_rundeck_key', to: 'set_rundeck_key', action: 'set_rundeck_key'
        post 'service_state', to: 'post_service_state', action: 'post_service_state'
        post 'run_ourcompose_role', to: 'post_run_ourcompose_role', action: 'post_run_ourcompose_role'
        post 'env_configuration', to: 'post_env_configuration', action: 'post_env_configuration'

        # Get Requests for latest
        get 'migration', to: 'get_migration', action: 'get_migration'
        get 'compositional_role', to: 'get_compositional_role', action: 'get_compositional_role'
        get 'health_check', to: 'get_health_check', action: 'get_health_check'
        get 'backup', to: 'get_backup', action: 'get_backup'
        get 'service_state', to: 'get_service_state', action: 'get_service_state'
        get 'env_configuration', to: 'get_env_configuration', action: 'get_env_configuration'

      end
      resource :proxy_logs, as: 'logs', path: 'logs', only: [:show] do
        get 'available', to: 'get_available_log_files', action: 'available_log_files'
        get 'get_file', to: 'get_log_file', action: 'log_file'
        get 'logfile_length', to: 'logfile_length', action: 'logfile_length'
      end
    end
  end

  get 'help', to: 'staticpages#help'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root 'staticpages#index'

end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
    <%= link_to root_path, class:"navbar-brand" do %>
        <img src="<%= asset_pack_path("media/images/LogoWithNameTransparentDark.png") %>" height="35" />
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <%- if controller_name != 'sessions' && current_user == nil %>
                <li class="nav-item">
                <%= link_to "Log in", new_session_path(resource_name), class:"nav-link" %>
                </li>
            <% end -%>
            <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
                <li class="nav-item">
                <%= link_to "Forgot your password?", new_password_path(resource_name), class:"nav-link" %>
                </li>
            <% end -%>
            <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
                <li class="nav-item">
                    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class:"nav-link" %>
                </li>
            <% end -%>
        </ul>
    </div>
    </div>
</nav>