config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations', 
    confirmations: 'users/confirmations'
  }

  devise_for :admins, skip: [:registrations]
  devise_scope :admin do
    unauthenticated :admin do
      root 'devise/sessions#new'
    end
    authenticated :admin do
      devise_for :admins, only: [:registrations], controllers: { registrations: 'admins/registrations' }
      root to: "customize#show", as: :authenticated_user
      resources :admins, only: [:index, :show]
      resource :customize, controller: 'customize', except: [:edit, :new] do
        get 'data', to: 'data'
      end
      resource :compositional_role_variable, as: 'env', path: 'env' do
        get 'env_vars', to: 'get_env_vars'
        post 'update', to: 'update', as: 'update_env'
      end 
      resource :services, controller:'services', except: [:edit, :new]
      namespace :rundeck do
        post 'migrate', to: 'migrate'
        get 'migration_status', to: 'migration_status'
        post 'run_compositional_role', to: 'run_compositional_role'
      end
      namespace :execution_abstraction do
        # Post Methods for Running Commands
        post 'migrate', to: 'post_migrate', action:'post_migrate'
        post 'compositional_role', to: 'post_compositional_role', action: 'post_compositional_role'
        post 'health_check', to: 'post_health_check', action: 'post_health_check'
        post 'run_backup', to: 'post_run_backup', action: 'post_run_backup'
        post 'set_rundeck_key', to: 'set_rundeck_key', action: 'set_rundeck_key'
        post 'service_state', to: 'post_service_state', action: 'post_service_state'
        post 'run_ourcompose_role', to: 'post_run_ourcompose_role', action: 'post_run_ourcompose_role'
        post 'env_configuration', to: 'post_env_configuration', action: 'post_env_configuration'

        # Get Requests for latest
        get 'migration', to: 'get_migration', action: 'get_migration'
        get 'compositional_role', to: 'get_compositional_role', action: 'get_compositional_role'
        get 'health_check', to: 'get_health_check', action: 'get_health_check'
        get 'backup', to: 'get_backup', action: 'get_backup'
        get 'service_state', to: 'get_service_state', action: 'get_service_state'
        get 'env_configuration', to: 'get_env_configuration', action: 'get_env_configuration'

      end
      resource :proxy_logs, as: 'logs', path: 'logs', only: [:show] do
        get 'available', to: 'get_available_log_files', action: 'available_log_files'
        get 'get_file', to: 'get_log_file', action: 'log_file'
        get 'logfile_length', to: 'logfile_length', action: 'logfile_length'
      end
    end
  end

  get 'help', to: 'staticpages#help'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root 'staticpages#index'

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container">
    <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to root_url, class:"navbar-brand" do %>
            Dashboard
        <% end %>
        </li>
        <li class="nav-item">
        <%= link_to customize_path, class:"nav-link" do %>
            Customize
        <% end %>
        </li>
        <li class="nav-item">
        <%= link_to env_path, class:"nav-link" do %>
            Environment Variables
        <% end %>
        </li>
        <li class="nav-item">
        <%= link_to logs_path, class:"nav-link" do %>
            Proxy Logs
        <% end %>
        </li>
    </ul>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown hidden-md-down">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://compositionalenterprises.ourcompose.com/bookstack">Documentation and Guides</a>
                    <a class="dropdown-item" href="https://ourcompose.com">Billing & Support</a>
                    <a class="dropdown-item" href="https://ourcomposecast.com">OurComposeCast</a>
                    <a class="dropdown-item" href="https://reddit.com/r/ourcompose">Community</a>
                    <a class="dropdown-item" href="https://gitlab.com/compositionalenterprises">Gitlab</a>
                    <a class="dropdown-item" href="https://compositionalenterprises.ourcompose.com/kanboard/public/board/245d06ce519a4deba6131ea58a65afa9efc0e6de584e04b08a81c4115322">Feature Roadmap</a>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Edit Account", edit_admin_registration_path, class:"dropdown-item" %>
                    <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class:"dropdown-item" %>
                </div>
            </li>
        </ul>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'bundle', 'data-turbolinks-track': 'load' %>
    <%= favicon_link_tag asset_pack_path("media/images/logo@16px.png") %>
  </head>

  <body>
    <%= yield %>
    <div class="corner-ribbon top-right sticky" style="background: #e56a19; z-index:1110">Alpha 1.0</div>
  </body>
</html>